from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.sql import func
from database import Base


class Worker(Base):
    __tablename__ = "workers"

    id                  = Column(Integer, primary_key=True, index=True)
    name                = Column(String, nullable=False)
    phone               = Column(String, unique=True, index=True, nullable=False)
    firebase_uid        = Column(String, unique=True, index=True, nullable=True)
    city                = Column(String, nullable=False)
    platform            = Column(String, nullable=False)
    upi                 = Column(String, nullable=True)
    avg_daily_income    = Column(Float, default=800)
    platform_hours      = Column(Float, default=8)
    trust_score         = Column(Integer, default=85)
    wallet_balance      = Column(Float, default=0.0)
    device_id           = Column(String, nullable=True, index=True)
    last_lat            = Column(Float, nullable=True)
    last_lon            = Column(Float, nullable=True)
    role                = Column(String, default="worker")
    onboarding_complete = Column(Boolean, default=True)
    created_at          = Column(DateTime, server_default=func.now())


class Claim(Base):
    __tablename__ = "claims"

    id           = Column(Integer, primary_key=True, index=True)
    worker_id    = Column(Integer, ForeignKey("workers.id", ondelete="CASCADE"), index=True, nullable=False)
    trigger_type = Column(String, nullable=False)
    amount       = Column(Float, nullable=False)
    status       = Column(String, default="APPROVED")
    rainfall_mm  = Column(Float, nullable=True)
    temp_celsius = Column(Float, nullable=True)
    created_at   = Column(DateTime, server_default=func.now())


class InsurancePolicy(Base):
    __tablename__ = "insurance_policies"

    id                = Column(Integer, primary_key=True, index=True)
    worker_id         = Column(Integer, ForeignKey("workers.id", ondelete="CASCADE"), index=True, nullable=False)
    plan_type         = Column(String, nullable=False)
    weekly_premium    = Column(Float, nullable=False)
    max_payout        = Column(Float, nullable=False)
    rain_threshold    = Column(Float, nullable=False)
    heat_threshold    = Column(Float, nullable=False)
    aqi_threshold     = Column(Integer, nullable=False)
    civil_coverage    = Column(Boolean, default=False)
    is_active         = Column(Boolean, default=True)
    razorpay_order_id = Column(String, nullable=True)
    created_at        = Column(DateTime, server_default=func.now())


class CommunityPost(Base):
    __tablename__ = "community_posts"

    id         = Column(Integer, primary_key=True, index=True)
    author     = Column(String, nullable=False)
    text       = Column(Text, nullable=False)
    city       = Column(String, nullable=True)
    platform   = Column(String, nullable=True)
    parent_id  = Column(Integer, nullable=True)
    likes      = Column(Integer, default=0)
    created_at = Column(DateTime, server_default=func.now())


class OTPRecord(Base):
    """Stores OTPs generated by fallback engine (when Twilio unavailable)."""
    __tablename__ = "otp_records"

    id         = Column(Integer, primary_key=True, index=True)
    phone      = Column(String, index=True, nullable=False)
    otp        = Column(String, nullable=False)
    used       = Column(Boolean, default=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=func.now())


class OTPThrottle(Base):
    __tablename__ = "otp_throttles"

    id                  = Column(Integer, primary_key=True, index=True)
    phone               = Column(String, index=True, nullable=False, unique=True)
    last_sent_at        = Column(DateTime, nullable=True)
    resend_available_at = Column(DateTime, nullable=True)
    failed_attempts     = Column(Integer, default=0)
    locked_until        = Column(DateTime, nullable=True)
    updated_at          = Column(DateTime, server_default=func.now(), onupdate=func.now())


class PremiumPool(Base):
    """Actuarial pool per city — tracks revenue vs. claims for business viability."""
    __tablename__ = "premium_pool"

    id             = Column(Integer, primary_key=True, index=True)
    city           = Column(String, index=True, nullable=False, unique=True)
    total_premiums = Column(Float, default=0.0)
    total_payouts  = Column(Float, default=0.0)
    reserve_ratio  = Column(Float, default=1.0)
    updated_at     = Column(DateTime, server_default=func.now(), onupdate=func.now())


class RefreshSession(Base):
    __tablename__ = "refresh_sessions"

    id         = Column(Integer, primary_key=True, index=True)
    token_id   = Column(String, unique=True, index=True, nullable=False)
    subject    = Column(String, index=True, nullable=False)
    role       = Column(String, nullable=False)
    token_hash = Column(String, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    revoked_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now())


class PaymentTransaction(Base):
    __tablename__ = "payment_transactions"

    id                  = Column(Integer, primary_key=True, index=True)
    worker_id           = Column(Integer, ForeignKey("workers.id", ondelete="CASCADE"), index=True, nullable=False)
    kind                = Column(String, nullable=False)
    status              = Column(String, nullable=False, default="created")
    provider_order_id   = Column(String, unique=True, index=True, nullable=False)
    provider_payment_id = Column(String, unique=True, index=True, nullable=True)
    plan_type           = Column(String, nullable=True)
    amount              = Column(Float, nullable=False)
    verified_at         = Column(DateTime, nullable=True)
    created_at          = Column(DateTime, server_default=func.now())
